[package]
name = "nsim"
version = "0.1.0"
authors = ["irfan sharif <irfanmahmoudsharif@gmail.com>"]

[lib]
name = "nlib"
path = "src/lib.rs"

[[bin]]
name = "nsim"
path = "src/main.rs"

[dependencies]
getopts = "0.2"
rand = "0.3"
streaming-stats = "0.1"
